### ISSUE TITLE
Compiler error after upgrading to 2.9.0 from 2.5.5

### ISSUE THREAD

**Issue by boggye** [cmeeren/Facil#58]
Hi,

I upgraded to Facil 2.9.0 (from 2.5.5) and now I get the following compilation error:

```
Error FS0193 : The module/namespace 'Facil.Runtime' from compilation unit 'Facil.Runtime' did not contain the namespace, module or type 'FacilReaderDisposer'
```
Any ideas about what could cause this error? I am targeting Net 6.0 in my project. Let me know if you need other information from me. I rolled back to version 2.5.5 and the app compiles fine now.

Thank you

**Comment by cmeeren** [comment]
My guess is you need to clean and re-build.

**Comment by boggye** [comment]
I did that but I still get the error.

**Comment by cmeeren** [comment]
Or even better, check out a fresh copy of your repo, upgrade the package in Notepad or similar, and first then open in your IDE and build.

**Comment by boggye** [comment]
> Have you tried deleting all your bin and obj folders and then rebuilding?

That did the trick. Thanks!!
